# Generated by Django 5.2.1 on 2025-07-15 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutritionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.IntegerField()),
                ("weight", models.FloatField()),
                ("age", models.IntegerField()),
                ("activity_level", models.FloatField()),
                ("goal", models.CharField()),
                ("diet_preference", models.CharField()),
                ("protein_preference", models.CharField()),
                ("bmr", models.IntegerField()),
                ("target_calories", models.IntegerField()),
                ("target_protein", models.IntegerField()),
                ("target_carbs", models.IntegerField()),
                ("target_fats", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition",
                        to="calorie.user",
                    ),
                ),
            ],
        ),
    ]
