# Generated by Django 5.2.1 on 2025-07-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calorie", "0002_alter_nutritionprofile_user_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionprofile",
            name="activity_level",
        ),
    ]
