# Generated by Django 5.2.1 on 2025-07-19 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calorie", "0005_dailylog_logentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
